import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '../../..');
const source = fs.readFileSync(path.join(root, 'src/apps-script/FinancialCoreRevenuePlan.gs'), 'utf8');
const definitions = {OPERATIONS:{sheetName:'10_Операции',headerRow:4,columns:[{label:'operation'}]},REFUNDS:{sheetName:'14_Возвраты',headerRow:4,columns:[{label:'refund'}]},SYS_PERIODS:{sheetName:'_SYS_PERIODS',headerRow:1,columns:[{label:'period'}]}};
function load(options={}) { const writes=[], sheets={}; Object.keys(definitions).forEach((key)=>{const schema=definitions[key], header=options.badHeader===key?['bad']:schema.columns.map((column)=>column.label);sheets[schema.sheetName]={getMaxColumns:()=>options.badColumns===key?0:schema.columns.length,getRange:()=>({getDisplayValues:()=>[header],setValue:()=>writes.push('setValue')})};}); const context={SpreadsheetApp:{getActiveSpreadsheet:()=>options.noSpreadsheet?null:{getSheetByName:(name)=>options.missingSheet===name?null:sheets[name]}},LC_getSchemaDefinition:(key)=>definitions[key],LC_validatePeriods:()=>options.periods||{valid:true}};vm.createContext(context);vm.runInContext(source,context);return {api:context,writes}; }
export function runFinancialCoreRevenueSuite() { const tests=[],test=(id,fn)=>{try{fn();tests.push({id,pass:true});}catch(error){tests.push({id,pass:false,message:error.message});}};test('FCR-01',()=>{const x=load(),r=x.api.LC_planFinancialCoreRevenue();assert.equal(r.valid,true);assert.equal(r.writeEnabled,false);assert.equal(r.metrics.length,4);assert.equal(x.writes.length,0);});test('FCR-02',()=>{const x=load({badHeader:'OPERATIONS'}),r=x.api.LC_validateFinancialCoreRevenue();assert.equal(r.valid,false);assert.ok(r.blockers.some((item)=>item.code==='FINANCIAL_CORE_SOURCE_HEADER_MISMATCH'));assert.equal(x.writes.length,0);});test('FCR-03',()=>{const x=load({periods:{valid:false}}),r=x.api.LC_planFinancialCoreRevenue();assert.equal(r.valid,false);assert.ok(r.blockers.some((item)=>item.code==='FINANCIAL_CORE_PERIODS_BLOCKED'));assert.equal(x.writes.length,0);});test('FCR-04',()=>{const x=load({noSpreadsheet:true}),r=x.api.LC_planFinancialCoreRevenue();assert.equal(r.valid,false);assert.ok(r.blockers.some((item)=>item.code==='FINANCIAL_CORE_SPREADSHEET_UNAVAILABLE'));});test('FCR-05',()=>{const x=load(),r=x.api.LC_planFinancialCoreRevenue();assert.equal(JSON.stringify(r).includes('setValue'),false);assert.equal(r.warnings[0].code,'FINANCIAL_CORE_FORMULAS_NOT_INSTALLED');});return {valid:tests.every((item)=>item.pass),tests}; }
