/**
 * Static technical configuration. User financial settings are forbidden here.
 * @type {!Object}
 */
var LC_APP_CONFIG = Object.freeze({
  APPLICATION_NAME: 'Lumiere Control', APPLICATION_VERSION: '0.1.0', DEV_BUILD_ID: '20260728-234500-direct-api',
  SCHEMA_VERSION: '1.0', BOOTSTRAP_VERSION: '1.0', SPECIFICATION_VERSION: '1.0',
  DEFAULT_CASH_MODULE_ENABLED: false, MANAGED_PROTECTION_PREFIX: 'LC_MANAGED_PROTECTION:',
  MENU_NAME: 'Lumiere Control', SYSTEM_SHEET_PREFIX: '_SYS_',
  SHEET_GROUPS: Object.freeze({MANAGEMENT: 'management', INPUT: 'input', REFERENCE: 'reference', SYSTEM: 'system'}),
  PROTECTION_MODES: Object.freeze({NONE: 'none', WARNING_ONLY: 'warning_only', SYSTEM_WARNING_ONLY: 'system_warning_only'}),
  LOG_LEVELS: Object.freeze({INFO: 'INFO', WARNING: 'WARNING', ERROR: 'ERROR'}),
  ERROR_CATEGORIES: Object.freeze({SCHEMA_ERROR: 'SCHEMA_ERROR', PROTECTION_ERROR: 'PROTECTION_ERROR', VERSION_ERROR: 'VERSION_ERROR', SYSTEM_ERROR: 'SYSTEM_ERROR'}),
  EVENT_TYPES: Object.freeze({WORKBOOK_BOOTSTRAP_STARTED: 'WORKBOOK_BOOTSTRAP_STARTED', SHEET_CREATED: 'SHEET_CREATED', SHEET_ALREADY_EXISTS: 'SHEET_ALREADY_EXISTS', SCHEMA_CREATED: 'SCHEMA_CREATED', SCHEMA_VERIFIED: 'SCHEMA_VERIFIED', SCHEMA_DRIFT: 'SCHEMA_DRIFT', LOOKUPS_CREATED: 'LOOKUPS_CREATED', LOOKUPS_VERIFIED: 'LOOKUPS_VERIFIED', LOOKUP_DRIFT: 'LOOKUP_DRIFT', PROTECTION_CREATED: 'PROTECTION_CREATED', PROTECTION_VERIFIED: 'PROTECTION_VERIFIED', WORKBOOK_BOOTSTRAP_COMPLETED: 'WORKBOOK_BOOTSTRAP_COMPLETED', WORKBOOK_INSPECTION_COMPLETED: 'WORKBOOK_INSPECTION_COMPLETED', SYSTEM_ERROR: 'SYSTEM_ERROR'})
});

/** Permanent read-only health endpoint for the DEV API executable. @return {!Object} */
function LC_apiHealthCheck() {
  return {ok:true,service:'lumiere-control',runtime:'apps-script',timestamp:new Date().toISOString(),scriptIdConfirmed:true,buildId:LC_APP_CONFIG.DEV_BUILD_ID};
}
