/** @return {!Object} */
function LC_planDataValidations() { var ss=_LCDV_active_(); if(!ss)return _LCDV_planResult_(false,[],[],[],[{code:'NO_ACTIVE_SPREADSHEET'}],[]); return _LCDV_plan_(ss); }
/** @return {!Object} */
function LC_bootstrapDataValidations() {
  var ss=_LCDV_active_(); if(!ss)return _LCDV_traceResult_(false,'data_validation_bootstrap_blocked',null,[],[],null,[{code:'NO_ACTIVE_SPREADSHEET'}],[],null);
  var lock=LockService.getScriptLock(); if(!lock.tryLock(5000))return _LCDV_traceResult_(false,'data_validation_bootstrap_blocked',null,[],[],null,[{code:'DATA_VALIDATION_LOCK_UNAVAILABLE'}],[],null);
  var started=[], succeeded=[], failed=null;
  try { var p=_LCDV_plan_(ss); if(!p.canApply)return _LCDV_traceResult_(false,'data_validation_bootstrap_blocked',p,started,succeeded,failed,p.blockers,p.warnings,null);
    p.actions.apply.forEach(function(a){var d=_LCDV_descriptor_(a);started.push(d);try{a.targetRange.setDataValidation(SpreadsheetApp.newDataValidation().requireValueInRange(a.sourceRange,true).setAllowInvalid(false).setHelpText('enumKey: '+a.enumKey+'; '+a.columnLabel+'; выберите значение из списка.').build());succeeded.push(d);}catch(e){failed=d;throw e;}});
    var v=LC_validateDataValidations();if(!v.valid)throw Error('DATA_VALIDATION_POSTCHECK_FAILED');return _LCDV_traceResult_(true,p.actions.apply.length?'data_validation_bootstrap_completed':'data_validations_already_aligned',p,started,succeeded,null,[],p.warnings,v);
  } catch(e) { return _LCDV_traceResult_(false,'data_validation_bootstrap_failed',null,started,succeeded,failed,[{code:'DATA_VALIDATION_RUNTIME_ERROR',message:String(e.message||e)}],[],null); } finally {lock.releaseLock();}
}
function _LCDV_descriptor_(a){return {schemaKey:a.schemaKey,sheetName:a.sheetName,columnName:a.columnName,enumKey:a.enumKey,targetRangeA1:a.targetRangeA1};}
function _LCDV_traceResult_(success,status,plan,started,succeeded,failed,blockers,warnings,validation){var r=_LCDV_bootResult_(success,status,success&&plan?plan.actions.apply:[],success&&plan?plan.actions.alreadyAligned:[],plan?plan.actions.unresolvedLookupValues:[],blockers,warnings,validation);r.partialChanges=!success&&started.length>0;r.potentiallyChangedRanges=success?[]:started;r.successfullyAppliedRanges=succeeded;r.failedRange=failed;r.error=status==='data_validation_bootstrap_failed'?blockers[0]:null;return r;}
/** @return {!Object} */
function LC_validateDataValidations() { var p=LC_planDataValidations(), aligned=p.actions.alreadyAligned.length, errors=p.blockers.slice();return {valid:errors.length===0,declaredEnumTargetCount:p.declaredEnumTargetCount,resolvableTargetCount:p.resolvableTargetCount,alignedTargetCount:aligned,unresolvedTargetCount:p.unresolvedTargetCount,errors:errors,warnings:p.warnings}; }
function _LCDV_plan_(ss){var defs=LC_getSchemaDefinitions(),lookups=LC_getLookupDefinitions(),ls=ss.getSheetByName('_SYS_LOOKUPS'),schema=LC_getSchemaDefinition('SYS_LOOKUPS'),targets=[],apply=[],aligned=[],unresolved=[],blockers=[],warnings=[];if(!ls){blockers.push({code:'SYS_LOOKUPS_SHEET_MISSING'});return _LCDV_planResult_(false,apply,aligned,unresolved,blockers,warnings,0,0);}var headers=ls.getRange(schema.headerRow,1,1,38).getDisplayValues()[0];Object.keys(defs).forEach(function(k){var s=defs[k],table=s.representation==='table'||(!s.representation&&s.columns.length&&!s.layout.length);if(!table)return;s.columns.forEach(function(c,i){if(c.type==='enum'&&c.enumKey&&c.editable&&!c.system)targets.push({schemaKey:k,schema:s,column:c,columnIndex:i+1});});});targets.forEach(function(t){var d=lookups.filter(function(x){return x.key===t.column.enumKey;})[0],i=schema.columns.map(function(x){return x.name;}).indexOf(t.column.enumKey),sheet=ss.getSheetByName(t.schema.sheetName);if(!d||i<0||!sheet||headers[i]!==schema.columns[i].label){blockers.push({code:'ENUM_LOOKUP_MAPPING_INVALID',schemaKey:t.schemaKey,columnName:t.column.name});return;}var vals=_LCDV_values_(ls,schema.headerRow+1,i+1),range=sheet.getRange(t.schema.headerRow+1,t.columnIndex,sheet.getMaxRows()-t.schema.headerRow,1);if(!vals.length){unresolved.push(_LCDV_action_(t,range,null,0,ls.getName()));warnings.push({code:'LOOKUP_VALUES_NOT_CONFIGURED',enumKey:t.column.enumKey});return;}var source=ls.getRange(schema.headerRow+1,i+1,vals.length,1),a=_LCDV_action_(t,range,source,vals.length);if(!_LCDV_validValues_(ls,schema.headerRow+1,i+1,vals,d)){blockers.push({code:'LOOKUP_SOURCE_INVALID',enumKey:t.column.enumKey});return;}var existing=range.getDisplayValues().map(function(r){return r[0];});for(var r=0;r<existing.length;r++)if(existing[r]&&vals.indexOf(existing[r])<0){blockers.push({code:'ENUM_EXISTING_VALUE_CONFLICT',sheetName:t.schema.sheetName,columnName:t.column.name,row:t.schema.headerRow+1+r,value:String(existing[r])});return;}var rules=range.getDataValidations(),allRules=rules.reduce(function(x,row){return x.concat(row);},[]),rule=allRules[0];if(allRules.some(function(x){return x&&!_LCDV_equivalent_(x,source);})){blockers.push({code:'DATA_VALIDATION_CONFLICT',sheetName:t.schema.sheetName,columnName:t.column.name});return;}if(rule&&allRules.every(function(x){return !!x;})){aligned.push(a);return;}if(rule){blockers.push({code:'DATA_VALIDATION_CONFLICT',sheetName:t.schema.sheetName,columnName:t.column.name});return;}apply.push(a);});return _LCDV_planResult_(blockers.length===0,apply,aligned,unresolved,blockers,warnings,targets.length,apply.length+aligned.length);}
function _LCDV_values_(s,r,c){var n=s.getLastRow();if(n<r)return[];var v=s.getRange(r,c,n-r+1,1).getDisplayValues().map(function(x){return x[0];});while(v.length&&!v[v.length-1])v.pop();return v;}
function _LCDV_validValues_(s,r,c,v,d){if(!v.length||v.some(function(x){return x==='';})||new Set(v).size!==v.length)return false;var all=_LCDV_values_(s,r,c);if(all.length!==v.length)return false;if(s.getRange(r,c,v.length,1).getFormulas().some(function(x){return x[0];}))return false;return d.valuesStatus!=='defined'||_LCDV_same_(v,d.values);}
function _LCDV_equivalent_(rule,source){try{var criterion=rule.getCriteriaValues()[0];return rule.getCriteriaType()===SpreadsheetApp.DataValidationCriteria.VALUE_IN_RANGE&&criterion.getA1Notation()===source.getA1Notation()&&criterion.getSheet().getName()===source.getSheet().getName()&&rule.getAllowInvalid()===false&&rule.getShowDropdown()===true;}catch(e){return false;}}
function _LCDV_action_(t,range,source,n,sourceSheetName){return {schemaKey:t.schemaKey,sheetName:t.schema.sheetName,columnName:t.column.name,columnLabel:t.column.label,columnIndex:t.columnIndex,enumKey:t.column.enumKey,targetRangeA1:range.getA1Notation(),sourceRangeA1:source?source.getA1Notation():null,sourceSheetName:source?source.getSheet().getName():sourceSheetName||null,sourceValueCount:n,targetRange:range,sourceRange:source};}
function _LCDV_planResult_(ok,a,b,u,x,w,d,r){return {valid:ok,canApply:ok,spreadsheetId:null,declaredEnumTargetCount:d||0,resolvableTargetCount:r||0,unresolvedTargetCount:u.length,actions:{apply:a,alreadyAligned:b,unresolvedLookupValues:u},blockers:x,warnings:w};}
function _LCDV_bootResult_(success,status,a,b,u,x,w,v){var p=LC_planDataValidations();return {success:success,status:status,declaredEnumTargetCount:p.declaredEnumTargetCount,appliedTargets:a,skippedAlignedTargets:b,unresolvedTargets:u,blockers:x,warnings:w,validation:v};}
function _LCDV_active_(){try{return SpreadsheetApp.getActiveSpreadsheet();}catch(e){return null;}}
function _LCDV_same_(a,b){return a.length===b.length&&a.every(function(x,i){return x===b[i];});}



