/** Recovers the approved demo fixture and builds a non-destructive Owner Desk. @return {!Object} */
function LC_recoverDemoAndBuildOwnerDesk() {
  var preflight = _LCDOD_preflight_();
  if (!preflight.valid) return _LCDOD_report_(false, 'demo_recovery_blocked', preflight, []);
  try {
    var changes=[];
    if (preflight.approvedPartial) {
      preflight.operationSheet.deleteRow(preflight.approvedPartial.sheetRowNumber);
      changes.push({sheetName:preflight.operationSchema.sheetName,deletedRow:preflight.approvedPartial.sheetRowNumber,recordId:'DEMO-OP-001'});
      preflight = _LCDOD_preflight_();
      if (!preflight.valid) return _LCDOD_report_(false, 'demo_recovery_blocked_after_approved_delete', preflight, changes);
    }
    if (preflight.operationsToAppend.length) preflight.operationSheet.getRange(preflight.operationSheet.getLastRow() + 1, 1, preflight.operationsToAppend.length, preflight.operationSchema.columns.length).setValues(preflight.operationsToAppend);
    if (preflight.refundsToAppend.length) preflight.refundSheet.getRange(preflight.refundSheet.getLastRow() + 1, 1, preflight.refundsToAppend.length, preflight.refundSchema.columns.length).setValues(preflight.refundsToAppend);
    if (preflight.deskState === 'absent') _LCDOD_buildDesk_(preflight.deskSheet, preflight.deskStartRow);
    SpreadsheetApp.flush();
    changes.push({sheetName:preflight.operationSchema.sheetName,appendedRows:preflight.operationsToAppend.length},{sheetName:preflight.refundSchema.sheetName,appendedRows:preflight.refundsToAppend.length},{sheetName:preflight.deskSchema.sheetName,action:preflight.deskState === 'absent' ? 'created' : 'already_present',range:'A' + preflight.deskStartRow + ':H' + (preflight.deskStartRow + 7)});
    return _LCDOD_report_(true, 'demo_recovery_completed', preflight, changes);
  } catch (error) { return _LCDOD_report_(false, 'demo_recovery_failed', preflight, [{code:'DEMO_RECOVERY_RUNTIME_ERROR',message:String(error.message || error)}]); }
}

function _LCDOD_preflight_() {
  var ss=SpreadsheetApp.getActiveSpreadsheet(), op=LC_getSchemaDefinition('OPERATIONS'), rf=LC_getSchemaDefinition('REFUNDS'), desk=LC_getSchemaDefinition('OWNER_DESK'), os=ss.getSheetByName(op.sheetName), rs=ss.getSheetByName(rf.sheetName), ds=ss.getSheetByName(desk.sheetName), blockers=[], expectedOps=_LCDOD_operations_(op), expectedRefunds=_LCDOD_refunds_(rf), opStates, rfStates;
  if (!os || !rs || !ds) blockers.push({code:'DEMO_RECOVERY_SHEET_UNAVAILABLE'});
  if (!blockers.length && (!_LCDOD_headers_(os,op)||!_LCDOD_headers_(rs,rf))) blockers.push({code:'DEMO_RECOVERY_SCHEMA_DRIFT'});
  opStates=blockers.length?[]:_LCDOD_classify_(os,op,expectedOps,'internal_operation_id'); rfStates=blockers.length?[]:_LCDOD_classify_(rs,rf,expectedRefunds,'refund_id');
  var allStates=opStates.concat(rfStates),approvedPartial=_LCDOD_approvedPartial_(opStates,op),unapprovedPartial=allStates.filter(function(x){return x.state==='partial_or_conflicting'&&(!approvedPartial||x.recordId!==approvedPartial.recordId);});
  if (unapprovedPartial.length) blockers.push({code:'DEMO_RECORD_PARTIAL_OR_CONFLICTING',records:unapprovedPartial.map(function(x){return x.recordId;})});
  if (!blockers.length) blockers=blockers.concat(_LCDOD_validateFixture_(os,op,expectedOps),_LCDOD_validateFixture_(rs,rf,expectedRefunds));
  var desk=_LCDOD_deskState_(ds); if (desk.state==='partial_or_conflicting') blockers.push({code:'OWNER_DESK_NO_SAFE_RANGE'});
  return {valid:!blockers.length,blockers:blockers,operationSchema:op,refundSchema:rf,deskSchema:desk,operationSheet:os,refundSheet:rs,deskSheet:ds,operations:opStates,refunds:rfStates,operationsToAppend:opStates.filter(function(x){return x.state==='absent';}).map(function(x){return x.row;}),refundsToAppend:rfStates.filter(function(x){return x.state==='absent';}).map(function(x){return x.row;}),approvedPartial:approvedPartial,deskStartRow:desk.startRow,deskState:desk.state,periodId:'2026-07',expected:{revenue:10900,refunds:500,netRevenue:10400}};
}

function _LCDOD_classify_(sheet,schema,expected,idName){var map=_LCDOD_map_(schema),last=sheet.getLastRow(),values=last>schema.headerRow?sheet.getRange(schema.headerRow+1,1,last-schema.headerRow,schema.columns.length).getValues():[],byId={};values.forEach(function(r,i){var id=String(r[map[idName]]||'');if(!byId[id])byId[id]=[];byId[id].push({row:r,sheetRowNumber:schema.headerRow+1+i});});return expected.map(function(row){var id=String(row[map[idName]]),found=byId[id]||[];if(!found.length)return{recordId:id,state:'absent',row:row};if(found.length!==1)return{recordId:id,state:'partial_or_conflicting',row:row,duplicateRecordCount:found.length};return _LCDOD_sameRow_(found[0].row,row)?{recordId:id,state:'exact_match',row:row,sheetRowNumber:found[0].sheetRowNumber}:{recordId:id,state:'partial_or_conflicting',row:row,sheetRowNumber:found[0].sheetRowNumber,actual:found[0].row.map(_LCDOD_primitive_)};});}
function _LCDOD_sameRow_(actual,expected){return expected.every(function(v,i){return v===''||v===null||v===undefined||String(actual[i])===String(v);});}
function _LCDOD_validateFixture_(sheet,schema,rows){var map=_LCDOD_map_(schema),checks=['operation_status','refund_method','refund_reason','source_type','duplicate_status','validation_status'],b=[];checks.forEach(function(name){if(map[name]===undefined)return;var rule=sheet.getRange(schema.headerRow+1,map[name]+1,1,1).getDataValidation();if(!rule)return;var raw=rule.getCriteriaValues()[0],allowed=Array.isArray(raw)?raw:(raw&&typeof raw.getValues==='function'?raw.getValues().reduce(function(a,r){return a.concat(r);},[]):[]);allowed=allowed.map(String).filter(Boolean);if(!allowed.length){b.push({code:'DEMO_LOOKUP_RULE_UNREADABLE',field:name});return;}rows.forEach(function(row){var value=row[map[name]];if(value!==''&&allowed.indexOf(String(value))<0)b.push({code:'DEMO_LOOKUP_VALUE_INVALID',field:name,value:String(value)});});});return b;}
function _LCDOD_approvedPartial_(states,schema){var candidate=states.filter(function(x){return x.recordId==='DEMO-OP-001'&&x.state==='partial_or_conflicting';});if(candidate.length!==1)return null;var sourceIndex=_LCDOD_map_(schema).source_system,actual=candidate[0].actual;if(actual[sourceIndex]!=='demo_fixture')return null;return candidate[0];}
function _LCDOD_deskState_(sheet){var start=30,rows=8,range=sheet.getRange(start,1,rows,8),values=range.getDisplayValues(),expected=_LCDOD_deskValues_();if(range.getMergedRanges().length)return{state:'partial_or_conflicting',startRow:start};if(_LCDOD_equal_(values,expected))return{state:'exact_match',startRow:start};return values.every(function(r){return r.every(function(v){return v==='';});})?{state:'absent',startRow:start}:{state:'partial_or_conflicting',startRow:start};}
function _LCDOD_deskValues_(){return [['Рабочий стол владельца','','','','','','',''],['Период','2026-07','Статус','Предварительные данные','','','',''],['Внимание','Данные за период заполнены не полностью','','','','','',''],['Выручка','10 900','Возвраты','500','Чистая выручка','10 400','',''],['Операционная прибыль','Недостаточно данных','Доступная владельцу сумма','Недостаточно данных','','','',''],['','','','','','','',''],['','','','','','','',''],['','','','','','','','']];}
function _LCDOD_buildDesk_(sheet,row){var values=_LCDOD_deskValues_();sheet.getRange(row,1,8,8).setValues(values);sheet.getRange(row,1,1,8).setBackground('#1f2937').setFontColor('#ffffff').setFontWeight('bold').setFontSize(16);sheet.getRange(row+3,1,1,6).setBackground('#e5e7eb').setFontWeight('bold');sheet.getRange(row+4,1,1,4).setBackground('#fef3c7');sheet.getRange(row+2,1,1,8).setBackground('#fef3c7').setFontColor('#92400e');}
function _LCDOD_operations_(s){var base={source_system:'demo_fixture',source_type:'Ручной ввод',duplicate_status:'Уникальная',validation_status:'Корректна'};return [['DEMO-OP-001','2026-07-05','Выполнена','DEMO-SVC-HAIR','DEMO-MASTER-01',1,3000,3000,true],['DEMO-OP-002','2026-07-12','Выполнена','DEMO-SVC-COLOR','DEMO-MASTER-02',1,6000,5400,true],['DEMO-OP-003','2026-07-17','Выполнена','DEMO-SVC-NAIL','DEMO-MASTER-01',1,2500,2500,true],['DEMO-OP-004','2026-07-22','Отменена','DEMO-SVC-HAIR','DEMO-MASTER-01',1,2800,0,false]].map(function(x){var v={internal_operation_id:x[0],operation_date:new Date(x[1]+'T00:00:00'),operation_status:x[2],service_id:x[3],master_id:x[4],quantity:x[5],list_price:x[6],charged_amount:x[7],included_in_calculation:x[8]};Object.keys(base).forEach(function(k){v[k]=base[k];});return _LCDOD_row_(s,v);});}
function _LCDOD_refunds_(s){return[_LCDOD_row_(s,{refund_id:'DEMO-REF-001',original_operation_id:'DEMO-OP-001',refund_date:new Date('2026-07-20T00:00:00'),refund_amount:500,refund_method:'Наличными',refund_reason:'Другое',source_type:'Ручной ввод',validation_status:'Корректна',included_in_calculation:true})];}
function _LCDOD_headers_(sh,s){return sh.getRange(s.headerRow,1,1,s.columns.length).getDisplayValues()[0].every(function(v,i){return v===s.columns[i].label;});}function _LCDOD_map_(s){var m={};s.columns.forEach(function(c,i){m[c.name]=i;});return m;}function _LCDOD_row_(s,v){var r=Array(s.columns.length).fill('');s.columns.forEach(function(c,i){if(Object.prototype.hasOwnProperty.call(v,c.name))r[i]=v[c.name];});return r;}function _LCDOD_primitive_(v){return v instanceof Date?v.toISOString():v===null?null:String(v);}function _LCDOD_equal_(a,b){return a.length===b.length&&a.every(function(row,i){return row.length===b[i].length&&row.every(function(value,j){return String(value)===String(b[i][j]);});});}function _LCDOD_report_(valid,status,p,changes){var r={valid:valid,status:status,periodId:p.periodId,expected:p.expected,operations:p.operations,refunds:p.refunds,deskStartRow:p.deskStartRow,blockers:p.blockers,changes:changes};Logger.log(JSON.stringify(r));return r;}
