function LC_bootstrapLookups(){var s=_LKB_activeSpreadsheet_();if(!s)return _LKB_result_(false,'lookup_bootstrap_blocked',null,[],[],[],[{code:'NO_ACTIVE_SPREADSHEET'}],[],null);var l=LockService.getScriptLock();if(!l.tryLock(5000))return _LKB_result_(false,'lookup_bootstrap_blocked','_SYS_LOOKUPS',[],[],[],[{code:'BOOTSTRAP_LOCK_UNAVAILABLE'}],[],null);var started=[];try{var p=_LKB_plan_(s);if(p.blockers.length)return _LKB_result_(false,'lookup_bootstrap_blocked',p.sheetName,[],p.skipped,p.preserved,p.blockers,p.warnings,null);p.toWrite.forEach(function(x){started.push(x.key);x.sheet.getRange(x.startRow,x.column,x.values.length,1).setValues(x.values.map(function(v){return[v];}));});var v=LC_validateLookupSheet();if(!v.valid)throw Error('LOOKUP_SHEET_VALIDATION_FAILED');return _LKB_result_(true,p.toWrite.length?'lookup_bootstrap_completed':'lookup_sheet_already_aligned',p.sheetName,started,p.skipped,p.preserved,[],p.warnings,v);}catch(e){return _LKB_result_(false,'lookup_bootstrap_failed','_SYS_LOOKUPS',started,[],[],[{code:'LOOKUP_BOOTSTRAP_RUNTIME_ERROR',message:String(e.message||e)}],[],null);}finally{l.releaseLock();}}
function LC_validateLookupSheet(){var s=_LKB_activeSpreadsheet_(),d=LC_getLookupDefinitions(),schema=LC_getSchemaDefinition('SYS_LOOKUPS'),st=LCLD_getMvpLookupStarterDefaults_(),e=[],w=[],pop=0,preserved=0;if(!s)return _LKB_validation_(false,d,st,0,0,[{code:'NO_ACTIVE_SPREADSHEET'}],[]);var sh=s.getSheetByName('_SYS_LOOKUPS');if(!sh)return _LKB_validation_(false,d,st,0,0,[{code:'SYS_LOOKUPS_SHEET_MISSING'}],[]);e=e.concat(_LKB_contract_(sh,schema,d,st));if(!e.length)d.forEach(function(x,i){var v=_LKB_values_(sh,2,i+1),m=_LKB_meta_(x,st);if(_LKB_formula_(sh,2,i+1))e.push({code:'LOOKUP_FORMULA_PRESENT',key:x.key});if(x.valuesStatus==='defined'){if(!_LKB_same_(v,x.values))e.push({code:'LOOKUP_DEFINED_VALUES_MISMATCH',key:x.key});}else if(m){if(m.defaultType==='fixed_mvp_default'){if(!_LKB_same_(v,m.values))e.push({code:'FIXED_STARTER_LOOKUP_VALUES_CONFLICT',key:x.key});else pop++;}else if(v.length){if(!_LKB_valid_(v))e.push({code:'CUSTOMIZABLE_LOOKUP_VALUES_INVALID',key:x.key});else{preserved++;w.push({code:'CUSTOMIZABLE_LOOKUP_VALUES_PRESERVED',key:x.key});}}else e.push({code:'CUSTOMIZABLE_LOOKUP_VALUES_INVALID',key:x.key});}else if(v.length){if(!_LKB_valid_(v))e.push({code:'KEY_ONLY_LOOKUP_VALUES_INVALID',key:x.key});else w.push({code:'KEY_ONLY_LOOKUP_VALUES_PRESERVED',key:x.key});}});return _LKB_validation_(e.length===0,d,st,pop,preserved,e,w);}
function _LKB_plan_(s){var d=LC_getLookupDefinitions(),schema=LC_getSchemaDefinition('SYS_LOOKUPS'),st=LCLD_getMvpLookupStarterDefaults_(),sh=s.getSheetByName('_SYS_LOOKUPS'),b=[],w=[],toWrite=[],skipped=[],preserved=[];if(!sh)return{sheetName:'_SYS_LOOKUPS',blockers:[{code:'SYS_LOOKUPS_SHEET_MISSING'}],warnings:w,toWrite:toWrite,skipped:skipped,preserved:preserved};b=b.concat(_LKB_contract_(sh,schema,d,st));if(!b.length)d.forEach(function(x,i){var v=_LKB_values_(sh,2,i+1),m=_LKB_meta_(x,st),formula=_LKB_formula_(sh,2,i+1),expected=x.valuesStatus==='defined'?x.values:m&&m.values;if(x.valuesStatus==='defined'||m&&m.defaultType==='fixed_mvp_default'){if(!v.length&&!formula)toWrite.push({sheet:sh,key:x.key,column:i+1,startRow:2,values:expected});else if(!formula&&_LKB_same_(v,expected))skipped.push(x.key);else b.push({code:x.valuesStatus==='defined'?'LOOKUP_DEFINED_VALUES_CONFLICT':'FIXED_STARTER_LOOKUP_VALUES_CONFLICT',key:x.key});}else if(m){if(v.length){if(formula||!_LKB_valid_(v))b.push({code:'CUSTOMIZABLE_LOOKUP_VALUES_INVALID',key:x.key});else{preserved.push(x.key);w.push({code:'CUSTOMIZABLE_LOOKUP_VALUES_PRESERVED',key:x.key});}}else toWrite.push({sheet:sh,key:x.key,column:i+1,startRow:2,values:m.values});}else if(v.length){if(formula||!_LKB_valid_(v))b.push({code:'KEY_ONLY_LOOKUP_VALUES_INVALID',key:x.key});else{preserved.push(x.key);w.push({code:'KEY_ONLY_LOOKUP_VALUES_PRESERVED',key:x.key});}}});return{sheetName:'_SYS_LOOKUPS',blockers:b,warnings:w,toWrite:toWrite,skipped:skipped,preserved:preserved};}
function _LKB_meta_(d,s){return s.lookups.filter(function(x){return x.key===d.key;})[0]||null;}
function _LKB_contract_(sh,s,d,st){var e=[];if(!s||s.columns.length!==38||d.length!==38||st.lookups.length!==20||st.alreadyDefinedLookups.length!==2)e.push({code:'LOOKUP_CONTRACT_INVALID'});else{var h=sh.getRange(1,1,1,38).getDisplayValues()[0],x=s.columns.map(function(c){return c.label;});if(!_LKB_same_(h,x))e.push({code:'SYS_LOOKUPS_HEADERS_MISMATCH'});}return e;}
function _LKB_values_(s,r,c){var n=s.getLastRow();if(n<r)return[];var v=s.getRange(r,c,n-r+1,1).getDisplayValues().map(function(x){return x[0];});while(v.length&&!v[v.length-1])v.pop();return v;}
function _LKB_formula_(s,r,c){var n=s.getLastRow();return n>=r&&s.getRange(r,c,n-r+1,1).getFormulas().some(function(x){return x[0]!=='';});}
function _LKB_valid_(v){return!!v.length&&!v.some(function(x){return x==='';})&&new Set(v).size===v.length;}
function _LKB_activeSpreadsheet_(){try{return SpreadsheetApp.getActiveSpreadsheet();}catch(e){return null;}}
function _LKB_same_(a,b){return a.length===b.length&&a.every(function(x,i){return x===b[i];});}
function _LKB_validation_(ok,d,st,pop,preserved,e,w){return{valid:ok,sheetName:'_SYS_LOOKUPS',lookupCount:d.length,definedCount:3,keyOnlyCount:35,starterDefaultCount:20,populatedStarterDefaultCount:pop,plainKeyOnlyCount:15,preservedCustomizableCount:preserved,errors:e,warnings:w};}
function _LKB_result_(ok,status,sheet,pop,skip,preserve,b,w,v){var r={success:ok,status:status,sheetName:sheet||'_SYS_LOOKUPS',lookupCount:38,definedCount:3,keyOnlyCount:35,starterDefaultCount:20,plainKeyOnlyCount:15,populatedKeys:pop,skippedKeys:skip,preservedKeys:preserve,populatedStarterKeys:pop,preservedCustomizableKeys:preserve,fixedStarterConflictKeys:b.filter(function(x){return x.code==='FIXED_STARTER_LOOKUP_VALUES_CONFLICT';}).map(function(x){return x.key;}),blockers:b,warnings:w,validation:v};return r;}
