var LCPR_FINANCIAL_PERIOD_CONTRACT={
  "contractVersion": "1.0",
  "status": "financial_period_engine_contract",
  "generatedAt": "2026-07-25T00:00:00.000Z",
  "granularity": {"primary":"calendar_month","timezoneSource":"book_timezone","periodIdFormat":"YYYY-MM","periodStart":"first_calendar_day_inclusive","periodEnd":"last_calendar_day_inclusive","outOfMvp":["calendar_week","calendar_quarter","custom_period"]},
  "periodStates": [
    {"state":"closed_actual","label":"Р—Р°РєСЂС‹С‚С‹Р№ С„Р°РєС‚РёС‡РµСЃРєРёР№ РїРµСЂРёРѕРґ","definition":"РџРѕРґС‚РІРµСЂР¶РґС‘РЅРЅС‹Р№ СЂРµР·СѓР»СЊС‚Р°С‚ Р·Р°РєСЂС‹С‚РѕРіРѕ РїРµСЂРёРѕРґР°.","allowedDataClasses":["actual","adjustment"],"mutable":false,"requiresExplicitAction":true,"transitionRules":["Р—Р°РєСЂС‹РІР°РµС‚СЃСЏ С‚РѕР»СЊРєРѕ РїРѕСЃР»Рµ РїРѕР»РЅРѕРіРѕ preflight.","РџРµСЂРµРѕС‚РєСЂС‹РІР°РµС‚СЃСЏ С‚РѕР»СЊРєРѕ СЏРІРЅС‹Рј РґРµР№СЃС‚РІРёРµРј СЃ РёСЃС‚РѕСЂРёРµР№."],"prohibitions":["РџСЂСЏРјРѕРµ СЂРµРґР°РєС‚РёСЂРѕРІР°РЅРёРµ РёСЃС…РѕРґРЅС‹С… С„Р°РєС‚РѕРІ.","РќРµР·Р°РјРµС‚РЅС‹Р№ РїРѕРІС‚РѕСЂРЅС‹Р№ РёРјРїРѕСЂС‚."]},
    {"state":"current_preliminary","label":"РўРµРєСѓС‰РёР№ РїСЂРµРґРІР°СЂРёС‚РµР»СЊРЅС‹Р№ РїРµСЂРёРѕРґ","definition":"РўРµРєСѓС‰РёР№ РЅРµР·Р°РєСЂС‹С‚С‹Р№ РєР°Р»РµРЅРґР°СЂРЅС‹Р№ РјРµСЃСЏС† СЃ С„Р°РєС‚РѕРј РЅР° РґР°С‚Сѓ.","allowedDataClasses":["preliminary_actual","forecast","plan","adjustment","estimate","opportunity"],"mutable":true,"requiresExplicitAction":false,"transitionRules":["РўРѕР»СЊРєРѕ РѕРґРёРЅ РїРµСЂРёРѕРґ РјРѕР¶РµС‚ РёРјРµС‚СЊ СЌС‚Рѕ СЃРѕСЃС‚РѕСЏРЅРёРµ.","РџСЂРѕРіРЅРѕР· РѕСЃС‚Р°С‚РєР° РїРѕРєР°Р·С‹РІР°РµС‚СЃСЏ РѕС‚РґРµР»СЊРЅРѕ РѕС‚ С„Р°РєС‚Р°."],"prohibitions":["РќР°Р·С‹РІР°С‚СЊ РїСЂРµРґРІР°СЂРёС‚РµР»СЊРЅС‹Р№ СЂРµР·СѓР»СЊС‚Р°С‚ РѕРєРѕРЅС‡Р°С‚РµР»СЊРЅРѕР№ РїСЂРёР±С‹Р»СЊСЋ.","РЎРјРµС€РёРІР°С‚СЊ С„Р°РєС‚ Рё РїСЂРѕРіРЅРѕР·."]},
    {"state":"forecast","label":"РџСЂРѕРіРЅРѕР·РЅС‹Р№ РїРµСЂРёРѕРґ","definition":"Р‘СѓРґСѓС‰РёР№ РєР°Р»РµРЅРґР°СЂРЅС‹Р№ РјРµСЃСЏС† СЃ РїР»Р°РЅР°РјРё Рё СЏРІРЅС‹РјРё РїСЂРµРґРїРѕСЃС‹Р»РєР°РјРё.","allowedDataClasses":["plan","forecast","scenario","estimate","opportunity"],"mutable":true,"requiresExplicitAction":false,"transitionRules":["РџСЂРё РЅР°СЃС‚СѓРїР»РµРЅРёРё РјРµСЃСЏС†Р° СЃС‚Р°РЅРѕРІРёС‚СЃСЏ current_preliminary.","РџСЂРµРґРїРѕСЃС‹Р»РєРё СЃРѕС…СЂР°РЅСЏСЋС‚СЃСЏ РґР»СЏ plan/fact."],"prohibitions":["РЎС‡РёС‚Р°С‚СЊ РїСЂРѕРіРЅРѕР· С„Р°РєС‚РѕРј.","РЎРѕР·РґР°РІР°С‚СЊ С„Р°РєС‚РёС‡РµСЃРєСѓСЋ РІС‹СЂСѓС‡РєСѓ, РїСЂРёР±С‹Р»СЊ РёР»Рё РґРµРЅРµР¶РЅС‹Р№ РѕСЃС‚Р°С‚РѕРє.","РџРµСЂРµРїРёСЃС‹РІР°С‚СЊ Р±Р°Р·РѕРІС‹Р№ РїСЂРѕРіРЅРѕР· СЃС†РµРЅР°СЂРёРµРј."]}
  ],
  "stateResolutionPriority":[{"priority":1,"condition":"explicit_close_marker","state":"closed_actual"},{"priority":2,"condition":"contains_book_current_date","state":"current_preliminary"},{"priority":3,"condition":"after_book_current_calendar_month","state":"forecast"},{"priority":4,"condition":"past_and_not_closed","blockerCode":"PAST_PERIOD_NOT_CLOSED"}],
  "dateAttributionRules":[
    {"input":"operation_service","periodDate":"actual_service_date","rule":"Р”Р°С‚Р° С„Р°РєС‚РёС‡РµСЃРєРѕРіРѕ РѕРєР°Р·Р°РЅРёСЏ СѓСЃР»СѓРіРё."},{"input":"expense","periodDate":"expense_recognition_date","rule":"Р”Р°С‚Р° РїСЂРёР·РЅР°РЅРёСЏ СЂР°СЃС…РѕРґР°."},{"input":"shift","periodDate":"shift_date","rule":"Р”Р°С‚Р° СЃРјРµРЅС‹."},{"input":"material","periodDate":"movement_or_usage_date","rule":"Р”Р°С‚Р° РґРІРёР¶РµРЅРёСЏ РёР»Рё РёСЃРїРѕР»СЊР·РѕРІР°РЅРёСЏ."},{"input":"refund","periodDate":"financial_reflection_date","rule":"Р”Р°С‚Р° С„РёРЅР°РЅСЃРѕРІРѕРіРѕ РѕС‚СЂР°Р¶РµРЅРёСЏ РІРѕР·РІСЂР°С‚Р°."},{"input":"obligation","periodDate":"due_date_and_payment_date_separate","rule":"РЎСЂРѕРє РѕР±СЏР·Р°С‚РµР»СЊСЃС‚РІР° Рё РґР°С‚Р° РѕРїР»Р°С‚С‹ РЅРµ СЃРјРµС€РёРІР°СЋС‚СЃСЏ."},{"input":"adjustment","periodDate":"adjusted_period_id","rule":"РџРµСЂРёРѕРґ РєРѕСЂСЂРµРєС‚РёСЂРѕРІРєРё С…СЂР°РЅРёС‚СЃСЏ РѕС‚РґРµР»СЊРЅРѕ РѕС‚ timestamp СЃРѕР·РґР°РЅРёСЏ."},{"input":"plan","periodDate":"explicit_period_id","rule":"РџР»Р°РЅ РѕС‚РЅРѕСЃРёС‚СЃСЏ Рє СЏРІРЅРѕ СѓРєР°Р·Р°РЅРЅРѕРјСѓ period_id."}
  ],
  "closingPolicy":{"requiresExplicitAction":true,"preflightRequirements":["no_blocking_data_quality_errors","no_incomplete_imports","no_staging_rows_pending_commit","valid_required_operations","valid_required_expenses","refunds_and_adjustments_reconciled","no_forbidden_duplicates","required_metrics_calculated","period_snapshot_created"],"prohibitions":["delete_rows","change_source_amounts","convert_opportunity_to_actual_loss","count_no_show_as_revenue","count_forecast_as_actual"]},
  "reopeningPolicy":{"requiresExplicitAction":true,"requiredAuditFields":["reason","author","timestamp"],"preservesPreviousSnapshot":true,"createsNewHistoryVersion":true,"temporaryState":"unclosed_until_reclosed","prohibitions":["free_edit_of_closed_period","delete_previous_history"]},
  "adjustmentPolicy":{"storedSeparatelyFromSourceFacts":true,"requiredFields":["adjustment_id","period_id","type","changed_measurement_or_amount","reason","author","timestamp"],"sourceReference":"recommended_when_available","affectsLatestActiveVersion":true,"preservesSnapshots":true,"prohibitions":["destroy_source_record","destroy_previous_snapshot"]},
  "metricClassification":["actual","preliminary_actual","plan","forecast","scenario","adjustment","estimate","opportunity"],
  "cashAndProfitRules":["Operating profit belongs to accrual period.","Cash balance is a state as of date.","Owner-withdrawable amount is not profit.","Owner-withdrawable amount requires obligations, reserves and constraints.","Month close does not automatically authorize withdrawal of all profit.","Forecast cash balance is not actual cash balance."],
  "blockerCodes":[
    {"code":"MULTIPLE_CURRENT_PRELIMINARY_PERIODS","severity":"blocker","description":"РќР°Р№РґРµРЅРѕ Р±РѕР»РµРµ РѕРґРЅРѕРіРѕ С‚РµРєСѓС‰РµРіРѕ РїСЂРµРґРІР°СЂРёС‚РµР»СЊРЅРѕРіРѕ РїРµСЂРёРѕРґР°.","blocksClosing":true,"blocksCalculation":true},{"code":"PAST_PERIOD_NOT_CLOSED","severity":"blocker","description":"РџСЂРѕС€Р»С‹Р№ РїРµСЂРёРѕРґ РЅРµ Р·Р°РєСЂС‹С‚.","blocksClosing":true,"blocksCalculation":true},{"code":"PERIOD_DATE_RANGE_INVALID","severity":"blocker","description":"Р”РёР°РїР°Р·РѕРЅ РґР°С‚ РїРµСЂРёРѕРґР° РЅРµ СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓРµС‚ РєР°Р»РµРЅРґР°СЂРЅРѕРјСѓ РјРµСЃСЏС†Сѓ.","blocksClosing":true,"blocksCalculation":true},{"code":"PERIOD_ID_DUPLICATE","severity":"blocker","description":"РРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ РїРµСЂРёРѕРґР° РЅРµ СѓРЅРёРєР°Р»РµРЅ.","blocksClosing":true,"blocksCalculation":true},{"code":"PERIOD_STATE_INVALID","severity":"blocker","description":"РЎРѕСЃС‚РѕСЏРЅРёРµ РїРµСЂРёРѕРґР° РЅРµРґРѕРїСѓСЃС‚РёРјРѕ.","blocksClosing":true,"blocksCalculation":true},{"code":"PERIOD_CLOSE_DATA_QUALITY_BLOCKED","severity":"blocker","description":"Р—Р°РєСЂС‹С‚РёРµ Р±Р»РѕРєРёСЂСѓРµС‚СЃСЏ РєР°С‡РµСЃС‚РІРѕРј РґР°РЅРЅС‹С….","blocksClosing":true,"blocksCalculation":false},{"code":"PERIOD_CLOSE_IMPORT_INCOMPLETE","severity":"blocker","description":"Р•СЃС‚СЊ РЅРµР·Р°РІРµСЂС€С‘РЅРЅС‹Р№ РёРјРїРѕСЂС‚.","blocksClosing":true,"blocksCalculation":false},{"code":"PERIOD_CLOSE_STAGING_NOT_EMPTY","severity":"blocker","description":"Р•СЃС‚СЊ staging-СЃС‚СЂРѕРєРё, РѕР¶РёРґР°СЋС‰РёРµ commit.","blocksClosing":true,"blocksCalculation":false},{"code":"PERIOD_CLOSE_CALCULATION_INCOMPLETE","severity":"blocker","description":"РќРµ СЂР°СЃСЃС‡РёС‚Р°РЅС‹ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РјРµС‚СЂРёРєРё.","blocksClosing":true,"blocksCalculation":true},{"code":"CLOSED_PERIOD_DIRECT_EDIT_FORBIDDEN","severity":"blocker","description":"РџСЂСЏРјРѕРµ СЂРµРґР°РєС‚РёСЂРѕРІР°РЅРёРµ Р·Р°РєСЂС‹С‚РѕРіРѕ РїРµСЂРёРѕРґР° Р·Р°РїСЂРµС‰РµРЅРѕ.","blocksClosing":true,"blocksCalculation":true},{"code":"PERIOD_REOPEN_REASON_REQUIRED","severity":"blocker","description":"Р”Р»СЏ РїРµСЂРµРѕС‚РєСЂС‹С‚РёСЏ РЅСѓР¶РµРЅ audit trail.","blocksClosing":true,"blocksCalculation":false},{"code":"PERIOD_ADJUSTMENT_AUDIT_FIELDS_REQUIRED","severity":"blocker","description":"Р”Р»СЏ РєРѕСЂСЂРµРєС‚РёСЂРѕРІРєРё РѕР±СЏР·Р°С‚РµР»СЊРЅС‹ audit fields.","blocksClosing":true,"blocksCalculation":true},{"code":"FACT_FORECAST_CLASSIFICATION_CONFLICT","severity":"blocker","description":"РЎРјРµС€Р°РЅС‹ С„Р°РєС‚ Рё РїСЂРѕРіРЅРѕР·.","blocksClosing":true,"blocksCalculation":true}
  ],
  "sourceReferences":["AGENTS.md: sections 3, 4, 7, 11","docs/FINANCIAL_LOGIC.md: sections 5, 8, 20-34, 54-55","docs/DATA_MODEL.md: periods, adjustments and history","docs/SYSTEM_SHEETS_PHYSICAL_CONTRACT.md: SYS_PERIODS","docs/adr/0001-documentation-source-hierarchy.md","docs/adr/0002-plan-fact-and-conditional-cash-module.md","docs/adr/0006-period-close-adjustments-and-history.md","docs/adr/0007-backup-and-range-protection.md","src/apps-script/SchemaDefinitions.gs: SYS_PERIODS"],
  "runtimeExpectations":{"futurePublicFunctions":["LC_planPeriodSetup","LC_bootstrapPeriods","LC_validatePeriods","LC_planPeriodClose","LC_closePeriod","LC_planPeriodReopen","LC_reopenPeriod"],"staticEmbeddingRequired":true,"localJsonReadForbidden":true,"fullPreflightBeforeWrite":true,"snapshotAndAuditTrailRequired":true,"idempotent":true,"planAndValidateReadOnly":true,"automaticPeriodCloseForbidden":true}
};
function LCPR_getFinancialPeriodContract_(){return LCPR_clone_(LCPR_FINANCIAL_PERIOD_CONTRACT);}
function LCPR_clone_(v){if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(LCPR_clone_);var r={};Object.keys(v).forEach(function(k){r[k]=LCPR_clone_(v[k]);});return r;}
