/** Static registry; it has no Google Sheets side effects. */
var LC_SHEET_REGISTRY = (function () {
  var G = LC_APP_CONFIG.SHEET_GROUPS, P = LC_APP_CONFIG.PROTECTION_MODES;
  var rows = [
    ['00_Старт',G.MANAGEMENT,1,0,1,0,null,3,0,'START','Старт','Начальная навигация'],['01_Рабочий стол',G.MANAGEMENT,2,0,1,0,null,3,0,'OWNER_DESK','Рабочий стол','Основные показатели и приоритетные действия'],['02_Качество данных',G.MANAGEMENT,3,0,1,0,null,3,0,'DATA_QUALITY_VIEW','Качество данных','Состояние качества исходных данных'],['03_Услуги',G.MANAGEMENT,4,0,1,0,null,3,0,'SERVICE_ANALYSIS','Услуги','Аналитика услуг'],['04_Команда',G.MANAGEMENT,5,0,1,0,null,3,0,'TEAM_ANALYSIS','Команда','Аналитика команды'],['05_Сценарии',G.MANAGEMENT,6,0,1,0,null,3,0,'SCENARIO_VIEW','Сценарии','Сохранённые сценарии'],['06_Решения',G.MANAGEMENT,7,0,1,0,5,5,1,'DECISIONS','Решения','Решения владельца'],
    ['10_Операции',G.INPUT,8,0,1,0,4,4,1,'OPERATIONS','Операции','Канонический ввод операций'],['11_Расходы',G.INPUT,9,0,1,0,4,4,1,'EXPENSES','Расходы','Операционные расходы'],['12_Смены',G.INPUT,10,0,1,0,4,4,1,'SHIFTS','Смены','Рабочие смены'],['13_Материалы',G.INPUT,11,0,1,0,4,4,1,'MATERIALS','Материалы','Нормативы и фактические материалы'],['14_Возвраты',G.INPUT,12,0,1,0,4,4,1,'REFUNDS','Возвраты','Отдельные записи возвратов'],['15_Обязательства',G.INPUT,13,0,0,1,12,12,1,'OBLIGATIONS','Обязательства','Условный денежный блок'],
    ['20_Настройки',G.REFERENCE,14,0,1,0,4,4,1,'SETTINGS','Настройки','Настройки книги'],['21_Услуги_справочник',G.REFERENCE,15,0,1,0,4,4,1,'SERVICES_REFERENCE','Услуги','Справочник услуг'],['22_Мастера_справочник',G.REFERENCE,16,0,1,0,4,4,1,'MASTERS_REFERENCE','Мастера','Справочник мастеров'],['23_Схемы_оплаты',G.REFERENCE,17,0,1,0,4,4,1,'COMPENSATION_SCHEMES','Схемы оплаты','Справочник схем оплаты'],['24_Планы',G.REFERENCE,18,0,1,0,4,4,1,'PLANS','Планы','Планы периода'],
    ['_SYS_PERIODS',G.SYSTEM,19,1,0,0,1,1,0,'SYS_PERIODS','Периоды','Системные периоды'],['_SYS_CALC',G.SYSTEM,20,1,0,0,1,1,0,'SYS_CALC','Расчёты','Системные рассчитанные метрики'],['_SYS_SERVICE_METRICS',G.SYSTEM,21,1,0,0,1,1,0,'SYS_SERVICE_METRICS','Метрики услуг','Системные метрики услуг'],['_SYS_MASTER_METRICS',G.SYSTEM,22,1,0,0,1,1,0,'SYS_MASTER_METRICS','Метрики мастеров','Системные метрики мастеров'],['_SYS_RECOMMENDATIONS',G.SYSTEM,23,1,0,0,1,1,0,'SYS_RECOMMENDATIONS','Рекомендации','Системные рекомендации'],['_SYS_DATA_QUALITY',G.SYSTEM,24,1,0,0,1,1,0,'SYS_DATA_QUALITY','Качество данных','Системные проблемы качества'],['_SYS_SCENARIOS',G.SYSTEM,25,1,0,0,1,1,0,'SYS_SCENARIOS','Сценарии','Системные сценарии'],['_SYS_ADJUSTMENTS',G.SYSTEM,26,1,0,0,1,1,0,'SYS_ADJUSTMENTS','Корректировки','Системные корректировки'],['_SYS_IMPORTS',G.SYSTEM,27,1,0,0,1,1,0,'SYS_IMPORTS','Импорты','Журнал batch импорта'],['_SYS_LOG',G.SYSTEM,28,1,0,0,1,1,0,'SYS_LOG','Журнал','Технический журнал'],['_SYS_LOOKUPS',G.SYSTEM,29,1,0,0,1,1,0,'SYS_LOOKUPS','Списки','Системные перечисления'],['_SYS_STAGING',G.SYSTEM,30,1,0,0,1,1,0,'SYS_STAGING','Staging','Временные строки до подтверждения'],['_SYS_IMPORT_MAPPINGS',G.SYSTEM,31,1,0,0,1,1,0,'SYS_IMPORT_MAPPINGS','Сопоставления','Профили сопоставления']];
  return Object.freeze(rows.map(function(r){return Object.freeze({name:r[0],group:r[1],order:r[2],isSystem:!!r[3],isVisibleByDefault:!!r[4],isConditional:!!r[5],headerRow:r[6],frozenRows:r[7],hasFilter:!!r[8],schemaKey:r[9],protectionMode:r[3]?P.SYSTEM_WARNING_ONLY:(r[1]===G.MANAGEMENT?P.NONE:P.WARNING_ONLY),title:r[10],instruction:r[11]});}));
}());
/** @return {!Array<!Object>} */ function LC_getSheetRegistry(){return JSON.parse(JSON.stringify(LC_SHEET_REGISTRY));}
/** @param {string} sheetName @return {?Object} */ function LC_getSheetDefinition(sheetName){var x=LC_SHEET_REGISTRY.filter(function(s){return s.name===sheetName;})[0];return x?JSON.parse(JSON.stringify(x)):null;}
/** @return {!Array<string>} */ function LC_getManagedSheetNames(){return LC_SHEET_REGISTRY.map(function(s){return s.name;});}
/** @return {!Object} */ function LC_validateSheetRegistry(){var r=LC_SHEET_REGISTRY,e=[];function n(a){return new Set(a).size===a.length;}if(r.length!==31)e.push('sheet_count');if(r.filter(function(s){return s.isSystem;}).length!==13)e.push('system_count');if(r.filter(function(s){return s.group==='management';}).length!==7)e.push('management_count');if(r.filter(function(s){return s.group==='input';}).length!==6)e.push('input_count');if(r.filter(function(s){return s.group==='reference';}).length!==5)e.push('reference_count');if(!n(r.map(function(s){return s.name;})))e.push('names');if(!n(r.map(function(s){return s.schemaKey;})))e.push('schema_keys');if(!n(r.map(function(s){return s.order;})))e.push('orders');for(var i=0;i<31;i++){if(r[i].order!==i+1)e.push('order_sequence');}return {valid:e.length===0,sheetCount:r.length,systemSheetCount:r.filter(function(s){return s.isSystem;}).length,managementSheetCount:7,inputSheetCount:6,referenceSheetCount:5,errors:e,warnings:[]};}
